// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// dl_distance
std::vector<unsigned int> dl_distance(std::string a, std::string b);
RcppExport SEXP DLDistance_dl_distance(SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< std::string >::type a(aSEXP);
    Rcpp::traits::input_parameter< std::string >::type b(bSEXP);
    __result = Rcpp::wrap(dl_distance(a, b));
    return __result;
END_RCPP
}
