# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
dl_distance <- function(a, b) {
    .Call('DLDistance_dl_distance', PACKAGE = 'DLDistance', a, b)
}

